<?php

namespace BinBundle\Repository;

/**
 * abscenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abscenseRepository extends \Doctrine\ORM\EntityRepository
{
}
