<?php

namespace BinBundle\Repository;

/**
 * categoryyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryyRepository extends \Doctrine\ORM\EntityRepository
{
}
