<?php

namespace BinBundle\Repository;

/**
 * firstnameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class firstnameRepository extends \Doctrine\ORM\EntityRepository
{
}
