<?php

namespace BinBundle\Repository;

/**
 * groupeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class groupeeRepository extends \Doctrine\ORM\EntityRepository
{
}
