<?php

namespace BinBundle\Repository;

/**
 * parenttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parenttRepository extends \Doctrine\ORM\EntityRepository
{
}
