<?php

namespace BinBundle\Repository;

/**
 * parentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parentRepository extends \Doctrine\ORM\EntityRepository
{
}
