<?php

namespace BinBundle\Repository;

/**
 * pupilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pupilRepository extends \Doctrine\ORM\EntityRepository
{
}
