<?php

namespace BinBundle\Repository;

/**
 * subjecttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subjecttRepository extends \Doctrine\ORM\EntityRepository
{
}
