<?php

namespace BinBundle\Repository;

/**
 * subjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subjectRepository extends \Doctrine\ORM\EntityRepository
{
}
