<?php

namespace BinBundle\Repository;

/**
 * teacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teacherRepository extends \Doctrine\ORM\EntityRepository
{
}
